services:
  cockroachdb:
    image: cockroachdb/cockroach:${COCKROACHDB_VERSION}
    command: start-single-node --insecure --http-addr=0.0.0.0:8080
    ports:
      - "${COCKROACHDB_PORT}:26257"
      - "${COCKROACHDB_UI_PORT}:8080"
    volumes:
      - cockroachdb-data:/cockroach/cockroach-data
    networks:
      - telecom-net
    healthcheck:
      test: [ "CMD", "/cockroach/cockroach", "sql", "--insecure", "-e", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  scylladb:
    image: scylladb/scylla:${SCYLLADB_VERSION}
    command: --smp 1 --memory 1G --developer-mode 1
    ports:
      - "${SCYLLADB_CQL_PORT}:9042"
    volumes:
      - scylladb-data:/var/lib/scylla
    networks:
      - telecom-net
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status | grep UN" ]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:8123"
      - "${CLICKHOUSE_TCP_PORT}:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
    networks:
      - telecom-net
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8123/ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:${KAFKA_VERSION}
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - telecom-net

  kamailio:
    image: ghcr.io/kamailio/kamailio-ci:${KAMAILIO_VERSION}
    ports:
      - "127.0.0.1:5060:5060/udp"
      - "127.0.0.1:5060:5060/tcp"
    volumes:
     - ./infra/dialer-kamailio/kamailio.cfg:/etc/kamailio/kamailio.cfg:ro
    networks:
      telecom-net:
        ipv4_address: 172.28.0.10
    healthcheck:
      test: [ "CMD-SHELL", "kamcmd core.uptime || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  net-tools:
    image: alpine:latest
    command: [ "sleep", "3600" ]
    networks:
      - telecom-net

  freeswitch:
    image: freeswitch-final-1.22
    ports:
      - "8021:8021"
      - "30000-30010:30000-30010/udp"
      - "7443:7443"
    volumes:
      - freeswitch-log:/usr/local/freeswitch/log
      - freeswitch-recordings:/usr/local/freeswitch/recordings
    networks:
      telecom-net:
        ipv4_address: 172.28.0.11
    depends_on:
      - kamailio
    healthcheck:
      test: [ "CMD-SHELL", "/usr/local/freeswitch/bin/fs_cli -x 'status' | grep -q 'UP'" ]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  telecom-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24

volumes:
  cockroachdb-data:
  scylladb-data:
  clickhouse-data:
  kafka-data:
  freeswitch-log:
  freeswitch-recordings:
