services:
  cockroachdb:
    image: cockroachdb/cockroach:${COCKROACHDB_VERSION}
    command: start-single-node --insecure --http-addr=0.0.0.0:8080
    ports:
      - "${COCKROACHDB_PORT}:26257"
      - "${COCKROACHDB_UI_PORT}:8080"
    volumes:
      - cockroachdb-data:/cockroach/cockroach-data
    networks:
      - telecom-net
    healthcheck:
      test: [ "CMD", "/cockroach/cockroach", "sql", "--insecure", "-e", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  scylladb:
    image: scylladb/scylla:${SCYLLADB_VERSION}
    command: --smp 1 --memory 1G --developer-mode 1
    ports:
      - "${SCYLLADB_CQL_PORT}:9042"
    volumes:
      - scylladb-data:/var/lib/scylla
    networks:
      - telecom-net
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status | grep UN" ]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:8123"
      - "${CLICKHOUSE_TCP_PORT}:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
    networks:
      - telecom-net
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8123/ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  telecom-net:
    driver: bridge

volumes:
  cockroachdb-data:
  scylladb-data:
  clickhouse-data: